#! /bin/bash

MONITOR=`chunkc tiling::query --monitor id`
DESKTOPS=`chunkc tiling::query --desktops-for-monitor $MONITOR`
FIRST=($DESKTOPS[0])
let DESKTOP_ID=$FIRST+$1-1
if [ -z $1 ]; then
    exit 1
fi;
#chunkc tiling::desktop --focus $DESKTOP_ID
echo $DESKTOP_ID
